/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "boost.browser-logs": [],
    "cashier.payment": [
        {
            "name": "id",
            "required": true
        }
    ],
    "cashier.webhook": [],
    "login": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "user-profile-information.update": [],
    "user-password.update": [],
    "password.confirmation": [],
    "password.confirm": [],
    "two-factor.login": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "sanctum.csrf-cookie": [],
    "stancl.tenancy.asset": [
        {
            "name": "path",
            "required": false
        }
    ],
    "api.version.current": [],
    "api.version.check": [],
    "api.system-monitoring.metrics": [],
    "api.system-monitoring.overview": [],
    "api.locale.index": [],
    "api.locale.update": [],
    "api.locale.translations": [
        {
            "name": "namespace",
            "required": false
        }
    ],
    "api.roles.index": [],
    "api.roles.store": [],
    "api.roles.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.roles.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.roles.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.roles.permissions.batch": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.roles.permissions.sync": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.permissions.index": [],
    "api.permissions.store": [],
    "api.permissions.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.permissions.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.permissions.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.permissions.grouped": [],
    "api.users.roles.index": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.users.roles.sync": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.users.permissions.index": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.users.permissions.sync": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.users.permissions.give": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.users.permissions.revoke": [
        {
            "name": "id",
            "required": true
        }
    ],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "locale.update": [],
    "dashboard": [],
    "stats": [],
    "security.dashboard": [],
    "updates": [],
    "leaves-employee": [],
    "leave-add": [],
    "leave-update": [],
    "leave-delete": [],
    "leaves.paginate": [],
    "leaves.stats": [],
    "attendance-employee": [],
    "attendance.current-user-punch": [],
    "getCurrentUserAttendanceForDate": [],
    "punchIn": [],
    "punchOut": [],
    "attendance.punch": [],
    "attendance.exportExcel": [],
    "attendance.exportAdminExcel": [],
    "attendance.exportAdminPdf": [],
    "attendance.exportPdf": [],
    "getAllUsersAttendanceForDate": [],
    "getPresentUsersForDate": [],
    "getAbsentUsersForDate": [],
    "getClientIp": [],
    "daily-works": [],
    "dailyWorks.paginate": [],
    "dailyWorks.all": [],
    "daily-works-summary": [],
    "daily-works-summary.filter": [],
    "dailyWorks.statistics": [],
    "dailyWorks.updateStatus": [],
    "dailyWorks.updateCompletionTime": [],
    "dailyWorks.updateSubmissionTime": [],
    "dailyWorks.updateAssigned": [],
    "dailyWorks.uploadRFI": [],
    "dailyWorks.rfiFiles.upload": [
        {
            "name": "dailyWork",
            "required": true,
            "binding": "id"
        }
    ],
    "dailyWorks.rfiFiles.index": [
        {
            "name": "dailyWork",
            "required": true,
            "binding": "id"
        }
    ],
    "dailyWorks.rfiFiles.delete": [
        {
            "name": "dailyWork",
            "required": true,
            "binding": "id"
        },
        {
            "name": "mediaId",
            "required": true
        }
    ],
    "dailyWorks.rfiFiles.download": [
        {
            "name": "dailyWork",
            "required": true,
            "binding": "id"
        },
        {
            "name": "mediaId",
            "required": true
        }
    ],
    "dailyWorks.add": [],
    "dailyWorks.update": [],
    "daily-works-summary.refresh": [],
    "dailyWorks.updateInspectionDetails": [],
    "dailyWorks.updateIncharge": [],
    "dailyWorks.assign": [],
    "dailyWorks.delete": [],
    "dailyWorks.export": [],
    "daily-works-summary.export": [],
    "daily-works-summary.statistics": [],
    "holidays": [],
    "holidays-add": [],
    "holidays-delete": [],
    "holidays-legacy": [],
    "profile": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "profile.update": [],
    "profile.delete": [],
    "profile.image.upload": [],
    "profile.image.remove": [],
    "profile.stats": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "profile.export": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "profile.trackView": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "education.update": [],
    "education.delete": [],
    "experience.update": [],
    "experience.delete": [],
    "emails": [],
    "leave-summary": [],
    "letters": [],
    "letters.paginate": [],
    "letters.update": [],
    "leaves": [],
    "leave-update-status": [],
    "leave.summary.exportExcel": [],
    "leave.summary.exportPdf": [],
    "leaves.analytics": [],
    "leaves.pending-approvals": [],
    "leaves.bulk-approve": [],
    "leaves.bulk-reject": [],
    "leaves.approve": [
        {
            "name": "id",
            "required": true
        }
    ],
    "leaves.reject": [
        {
            "name": "id",
            "required": true
        }
    ],
    "leaves.bulk.validate": [],
    "leaves.bulk.store": [],
    "leaves.bulk.leave-types": [],
    "leaves.bulk.calendar-data": [],
    "leaves.bulk.delete": [],
    "leave-settings": [],
    "add-leave-type": [],
    "update-leave-type": [
        {
            "name": "id",
            "required": true
        }
    ],
    "delete-leave-type": [
        {
            "name": "id",
            "required": true
        }
    ],
    "employees": [],
    "employees.paginate": [],
    "employees.stats": [],
    "departments": [],
    "api.departments": [],
    "departments.stats": [],
    "departments.store": [],
    "departments.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "departments.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "departments.delete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "users.update-department": [
        {
            "name": "id",
            "required": true
        }
    ],
    "jurisdiction": [],
    "dailyWorks.import": [],
    "dailyWorks.downloadTemplate": [],
    "holiday-add": [],
    "holiday-delete": [],
    "users": [],
    "users.paginate": [],
    "users.stats": [],
    "profiles.search": [],
    "users.store": [],
    "addUser": [],
    "users.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "users.toggleStatus": [
        {
            "name": "id",
            "required": true
        }
    ],
    "users.updateRole": [
        {
            "name": "id",
            "required": true
        }
    ],
    "users.updateAttendanceType": [
        {
            "name": "id",
            "required": true
        }
    ],
    "users.updateReportTo": [
        {
            "name": "id",
            "required": true
        }
    ],
    "user.updateDepartment": [
        {
            "name": "id",
            "required": true
        }
    ],
    "user.updateDesignation": [
        {
            "name": "id",
            "required": true
        }
    ],
    "user.updateRole": [
        {
            "name": "id",
            "required": true
        }
    ],
    "user.toggleStatus": [
        {
            "name": "id",
            "required": true
        }
    ],
    "user.updateAttendanceType": [
        {
            "name": "id",
            "required": true
        }
    ],
    "user.updateReportTo": [
        {
            "name": "id",
            "required": true
        }
    ],
    "users.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "user.delete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "user.devices": [],
    "user.devices.deactivate": [
        {
            "name": "deviceId",
            "required": true
        }
    ],
    "admin.users.devices": [
        {
            "name": "userId",
            "required": true
        }
    ],
    "admin.users.devices.reset": [
        {
            "name": "userId",
            "required": true
        }
    ],
    "admin.users.devices.toggle": [
        {
            "name": "userId",
            "required": true
        }
    ],
    "admin.users.devices.deactivate": [
        {
            "name": "userId",
            "required": true
        },
        {
            "name": "deviceId",
            "required": true
        }
    ],
    "update-company-settings": [],
    "admin.settings.company": [],
    "roles-settings": [],
    "attendances": [],
    "timesheet": [],
    "attendancesAdmin.paginate": [],
    "getUserLocationsForDate": [],
    "admin.getPresentUsersForDate": [],
    "admin.getAbsentUsersForDate": [],
    "attendance.monthlyStats": [],
    "check-user-locations-updates": [
        {
            "name": "date",
            "required": true
        }
    ],
    "check-timesheet-updates": [
        {
            "name": "date",
            "required": true
        },
        {
            "name": "month",
            "required": false
        }
    ],
    "attendance.mark-as-present": [],
    "attendance.bulk-mark-as-present": [],
    "attendance.myMonthlyStats": [],
    "attendance-settings.index": [],
    "attendance-settings.update": [],
    "attendance-types.store": [],
    "attendance-types.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance-types.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance-types.addItem": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance-types.removeItem": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance-types.generateQr": [
        {
            "name": "id",
            "required": true
        }
    ],
    "settings.hr.onboarding": [],
    "settings.hr.skills": [],
    "settings.hr.benefits": [],
    "settings.hr.safety": [],
    "settings.hr.documents": [],
    "settings.hr.onboarding.update": [],
    "settings.hr.skills.update": [],
    "settings.hr.benefits.update": [],
    "settings.hr.safety.update": [],
    "settings.hr.documents.update": [],
    "allTasks": [],
    "filterTasks": [],
    "addTask": [],
    "showWorkLocations": [],
    "allWorkLocations": [],
    "addWorkLocation": [],
    "deleteWorkLocation": [],
    "updateWorkLocation": [],
    "allTasksSE": [],
    "filterTasksSE": [],
    "showTasksSE": [],
    "addTaskSE": [],
    "updateInspectionDetails": [],
    "updateTaskStatus": [],
    "assignTask": [],
    "updateCompletionDateTimeSE": [],
    "showDailySummarySE": [],
    "filterSummarySE": [],
    "getLatestTimestamp": [],
    "dailySummaryJSON": [],
    "showReports": [],
    "allReports": [],
    "addReport": [],
    "deleteReport": [],
    "updateReport": [],
    "attachReport": [],
    "detachReport": [],
    "admin.roles-management": [],
    "admin.roles.audit": [],
    "admin.roles.export": [],
    "admin.roles.metrics": [],
    "admin.roles.snapshot": [],
    "admin.roles.store": [],
    "admin.roles.clone": [],
    "admin.roles.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.roles.update-permission": [],
    "admin.roles.toggle-permission": [],
    "admin.roles.update-module": [],
    "admin.roles.bulk-operation": [],
    "admin.roles.batch-permissions": [
        {
            "name": "role",
            "required": true
        }
    ],
    "admin.roles.delete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.roles.initialize-enterprise": [],
    "admin.roles.test": [],
    "modules.index": [],
    "modules.api.index": [],
    "modules.statistics": [],
    "modules.check-access": [],
    "modules.store": [],
    "modules.sub-modules.store": [
        {
            "name": "module",
            "required": true
        }
    ],
    "modules.components.store": [
        {
            "name": "subModule",
            "required": true
        }
    ],
    "modules.update": [
        {
            "name": "module",
            "required": true
        }
    ],
    "modules.sub-modules.update": [
        {
            "name": "subModule",
            "required": true
        }
    ],
    "modules.components.update": [
        {
            "name": "component",
            "required": true
        }
    ],
    "modules.sync-permissions": [
        {
            "name": "module",
            "required": true
        }
    ],
    "modules.sub-modules.sync-permissions": [
        {
            "name": "subModule",
            "required": true
        }
    ],
    "modules.components.sync-permissions": [
        {
            "name": "component",
            "required": true
        }
    ],
    "modules.destroy": [
        {
            "name": "module",
            "required": true
        }
    ],
    "modules.sub-modules.destroy": [
        {
            "name": "subModule",
            "required": true
        }
    ],
    "modules.components.destroy": [
        {
            "name": "component",
            "required": true
        }
    ],
    "admin.roles.debug": [],
    "admin.roles.debug.refresh-cache": [],
    "admin.roles.debug.test-role": [],
    "admin.roles.debug.test-permission": [],
    "admin.system-monitoring": [],
    "admin.errors.resolve": [
        {
            "name": "errorId",
            "required": true
        }
    ],
    "admin.system-report": [],
    "admin.optimization-report": [],
    "crm.index": [],
    "crm.leads": [],
    "crm.leads.store": [],
    "crm.customers.index": [],
    "crm.opportunities.index": [],
    "crm.pipeline": [],
    "crm.reports": [],
    "crm.settings": [],
    "fms.index": [],
    "fms.accounts-payable": [],
    "fms.accounts-payable.store": [],
    "fms.accounts-receivable": [],
    "fms.accounts-receivable.store": [],
    "fms.general-ledger": [],
    "fms.general-ledger.store": [],
    "fms.reports.index": [],
    "fms.reports.generate": [],
    "fms.budgets.index": [],
    "fms.budgets.store": [],
    "fms.expenses": [],
    "fms.expenses.store": [],
    "fms.invoices": [],
    "fms.invoices.store": [],
    "fms.settings": [],
    "fms.settings.update": [],
    "pos.index": [],
    "pos.terminal": [],
    "pos.sales.index": [],
    "pos.sales.process": [],
    "pos.products": [],
    "pos.products.barcode": [
        {
            "name": "barcode",
            "required": true
        }
    ],
    "pos.customers": [],
    "pos.payments": [],
    "pos.reports": [],
    "pos.settings": [],
    "pos.settings.update": [],
    "ims.index": [],
    "ims.products": [],
    "ims.products.store": [],
    "ims.warehouse": [],
    "ims.warehouse.store": [],
    "ims.stock-movements": [],
    "ims.stock-movements.store": [],
    "ims.suppliers": [],
    "ims.suppliers.store": [],
    "ims.purchase-orders": [],
    "ims.purchase-orders.store": [],
    "ims.reports": [],
    "ims.settings": [],
    "ims.settings.update": [],
    "lms.index": [],
    "lms.courses.index": [],
    "lms.courses.store": [],
    "lms.students": [],
    "lms.students.store": [],
    "lms.students.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "lms.students.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "lms.instructors": [],
    "lms.instructors.store": [],
    "lms.instructors.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "lms.instructors.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "lms.assessments.index": [],
    "lms.assessments.store": [],
    "lms.certificates": [],
    "lms.certificates.store": [],
    "lms.certificates.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "lms.certificates.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "lms.reports": [],
    "designations.index": [],
    "designations.json": [],
    "designations.stats": [],
    "designations.store": [],
    "designations.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "designations.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "designations.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "designations.list": [],
    "api.designations.list": [],
    "departments.list": [],
    "users.managers.list": [],
    "updateFcmToken": [],
    "service-worker": [],
    "public.events.index": [],
    "public.events.show": [
        {
            "name": "slug",
            "required": true
        }
    ],
    "public.events.register": [
        {
            "name": "slug",
            "required": true
        }
    ],
    "public.events.registration-success": [
        {
            "name": "slug",
            "required": true
        },
        {
            "name": "token",
            "required": true
        }
    ],
    "public.events.check-registration": [],
    "public.events.download-token": [
        {
            "name": "token",
            "required": true
        }
    ],
    "events.create": [],
    "events.store": [],
    "events.index": [],
    "events.analytics": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "events.show": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "events.duplicate": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "events.edit": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "events.update": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "events.toggle-publish": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "events.destroy": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "sub-events.store": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "sub-events.update": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        },
        {
            "name": "subEvent",
            "required": true,
            "binding": "id"
        }
    ],
    "sub-events.destroy": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        },
        {
            "name": "subEvent",
            "required": true,
            "binding": "id"
        }
    ],
    "sub-events.reorder": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "sub-events.toggle-active": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        },
        {
            "name": "subEvent",
            "required": true,
            "binding": "id"
        }
    ],
    "events.registrations.index": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "events.registrations.show": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        },
        {
            "name": "registration",
            "required": true,
            "binding": "id"
        }
    ],
    "events.registrations.approve": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        },
        {
            "name": "registration",
            "required": true,
            "binding": "id"
        }
    ],
    "events.registrations.reject": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        },
        {
            "name": "registration",
            "required": true,
            "binding": "id"
        }
    ],
    "events.registrations.cancel": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        },
        {
            "name": "registration",
            "required": true,
            "binding": "id"
        }
    ],
    "events.registrations.verify-payment": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        },
        {
            "name": "registration",
            "required": true,
            "binding": "id"
        }
    ],
    "events.registrations.bulk-approve": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "events.registrations.bulk-reject": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "events.registrations.export-csv": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "events.registrations.export-pdf": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "events.registrations.print-token": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        },
        {
            "name": "registration",
            "required": true,
            "binding": "id"
        }
    ],
    "crm.dashboard": [],
    "crm.customers.create": [],
    "crm.customers.edit": [
        {
            "name": "customer",
            "required": true,
            "binding": "id"
        }
    ],
    "crm.customers.store": [],
    "crm.customers.update": [
        {
            "name": "customer",
            "required": true,
            "binding": "id"
        }
    ],
    "crm.customers.destroy": [
        {
            "name": "customer",
            "required": true,
            "binding": "id"
        }
    ],
    "crm.opportunities.create": [],
    "crm.opportunities.edit": [
        {
            "name": "opportunity",
            "required": true
        }
    ],
    "crm.opportunities.store": [],
    "crm.opportunities.update": [
        {
            "name": "opportunity",
            "required": true
        }
    ],
    "crm.opportunities.destroy": [
        {
            "name": "opportunity",
            "required": true
        }
    ],
    "crm.interactions.index": [],
    "crm.interactions.create": [],
    "crm.interactions.edit": [
        {
            "name": "interaction",
            "required": true
        }
    ],
    "crm.interactions.store": [],
    "crm.interactions.update": [
        {
            "name": "interaction",
            "required": true
        }
    ],
    "crm.interactions.destroy": [
        {
            "name": "interaction",
            "required": true
        }
    ],
    "fms.dashboard": [],
    "fms.transactions.index": [],
    "fms.transactions.create": [],
    "fms.transactions.edit": [
        {
            "name": "transaction",
            "required": true,
            "binding": "id"
        }
    ],
    "fms.transactions.store": [],
    "fms.transactions.update": [
        {
            "name": "transaction",
            "required": true,
            "binding": "id"
        }
    ],
    "fms.transactions.destroy": [
        {
            "name": "transaction",
            "required": true,
            "binding": "id"
        }
    ],
    "fms.accounts.index": [],
    "fms.accounts.create": [],
    "fms.accounts.edit": [
        {
            "name": "account",
            "required": true
        }
    ],
    "fms.accounts.store": [],
    "fms.accounts.update": [
        {
            "name": "account",
            "required": true
        }
    ],
    "fms.accounts.destroy": [
        {
            "name": "account",
            "required": true
        }
    ],
    "fms.reports.show": [
        {
            "name": "report",
            "required": true
        }
    ],
    "fms.budgets.create": [],
    "fms.budgets.edit": [
        {
            "name": "budget",
            "required": true
        }
    ],
    "fms.budgets.update": [
        {
            "name": "budget",
            "required": true
        }
    ],
    "fms.budgets.destroy": [
        {
            "name": "budget",
            "required": true
        }
    ],
    "pos.dashboard": [],
    "pos.sales.create": [],
    "pos.sales.edit": [
        {
            "name": "sale",
            "required": true,
            "binding": "id"
        }
    ],
    "pos.sales.store": [],
    "pos.sales.update": [
        {
            "name": "sale",
            "required": true,
            "binding": "id"
        }
    ],
    "pos.sales.destroy": [
        {
            "name": "sale",
            "required": true,
            "binding": "id"
        }
    ],
    "pos.orders.index": [],
    "pos.orders.create": [],
    "pos.orders.edit": [
        {
            "name": "order",
            "required": true
        }
    ],
    "pos.orders.store": [],
    "pos.orders.update": [
        {
            "name": "order",
            "required": true
        }
    ],
    "pos.orders.destroy": [
        {
            "name": "order",
            "required": true
        }
    ],
    "pos.cashier": [],
    "pos.cashier.process": [],
    "ims.dashboard": [],
    "ims.items.index": [],
    "ims.items.create": [],
    "ims.items.edit": [
        {
            "name": "item",
            "required": true,
            "binding": "id"
        }
    ],
    "ims.items.store": [],
    "ims.items.update": [
        {
            "name": "item",
            "required": true,
            "binding": "id"
        }
    ],
    "ims.items.destroy": [
        {
            "name": "item",
            "required": true,
            "binding": "id"
        }
    ],
    "ims.stock.index": [],
    "ims.stock.adjustment": [],
    "ims.stock.adjust": [],
    "ims.transfers.index": [],
    "ims.transfers.create": [],
    "ims.transfers.edit": [
        {
            "name": "transfer",
            "required": true
        }
    ],
    "ims.transfers.store": [],
    "ims.transfers.update": [
        {
            "name": "transfer",
            "required": true
        }
    ],
    "ims.transfers.destroy": [
        {
            "name": "transfer",
            "required": true
        }
    ],
    "lms.dashboard": [],
    "lms.courses.create": [],
    "lms.courses.edit": [
        {
            "name": "course",
            "required": true,
            "binding": "id"
        }
    ],
    "lms.courses.show": [
        {
            "name": "course",
            "required": true,
            "binding": "id"
        }
    ],
    "lms.courses.update": [
        {
            "name": "course",
            "required": true,
            "binding": "id"
        }
    ],
    "lms.courses.destroy": [
        {
            "name": "course",
            "required": true,
            "binding": "id"
        }
    ],
    "lms.enrollments.index": [],
    "lms.enrollments.create": [],
    "lms.enrollments.edit": [
        {
            "name": "enrollment",
            "required": true
        }
    ],
    "lms.enrollments.store": [],
    "lms.enrollments.update": [
        {
            "name": "enrollment",
            "required": true
        }
    ],
    "lms.enrollments.destroy": [
        {
            "name": "enrollment",
            "required": true
        }
    ],
    "lms.assessments.create": [],
    "lms.assessments.edit": [
        {
            "name": "assessment",
            "required": true
        }
    ],
    "lms.assessments.show": [
        {
            "name": "assessment",
            "required": true
        }
    ],
    "lms.assessments.update": [
        {
            "name": "assessment",
            "required": true
        }
    ],
    "lms.assessments.destroy": [
        {
            "name": "assessment",
            "required": true
        }
    ],
    "scm.dashboard": [],
    "scm.suppliers.index": [],
    "scm.suppliers.create": [],
    "scm.suppliers.edit": [
        {
            "name": "supplier",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.suppliers.store": [],
    "scm.suppliers.update": [
        {
            "name": "supplier",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.suppliers.destroy": [
        {
            "name": "supplier",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.purchases.index": [],
    "scm.purchases.create": [],
    "scm.purchases.edit": [
        {
            "name": "purchase",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.purchases.store": [],
    "scm.purchases.update": [
        {
            "name": "purchase",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.purchases.destroy": [
        {
            "name": "purchase",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.logistics.index": [],
    "scm.logistics.create": [],
    "scm.logistics.edit": [
        {
            "name": "logistic",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.logistics.store": [],
    "scm.logistics.update": [
        {
            "name": "logistic",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.logistics.delete": [
        {
            "name": "logistic",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.procurement.index": [],
    "scm.procurement.create": [],
    "scm.procurement.show": [
        {
            "name": "procurementRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.procurement.edit": [
        {
            "name": "procurementRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.procurement.store": [],
    "scm.procurement.update": [
        {
            "name": "procurementRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.procurement.destroy": [
        {
            "name": "procurementRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.procurement.approve": [
        {
            "name": "procurementRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.procurement.reject": [
        {
            "name": "procurementRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.demand-forecast.index": [],
    "scm.demand-forecast.create": [],
    "scm.demand-forecast.show": [
        {
            "name": "demandForecast",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.demand-forecast.edit": [
        {
            "name": "demandForecast",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.demand-forecast.store": [],
    "scm.demand-forecast.update": [
        {
            "name": "demandForecast",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.demand-forecast.destroy": [
        {
            "name": "demandForecast",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.production-plan.index": [],
    "scm.production-plan.create": [],
    "scm.production-plan.show": [
        {
            "name": "productionPlan",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.production-plan.edit": [
        {
            "name": "productionPlan",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.production-plan.store": [],
    "scm.production-plan.update": [
        {
            "name": "productionPlan",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.production-plan.destroy": [
        {
            "name": "productionPlan",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.production-plan.start": [
        {
            "name": "productionPlan",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.production-plan.complete": [
        {
            "name": "productionPlan",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.return-management.index": [],
    "scm.return-management.create": [],
    "scm.return-management.show": [
        {
            "name": "returnRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.return-management.edit": [
        {
            "name": "returnRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.return-management.store": [],
    "scm.return-management.update": [
        {
            "name": "returnRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.return-management.destroy": [
        {
            "name": "returnRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.return-management.approve": [
        {
            "name": "returnRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.return-management.reject": [
        {
            "name": "returnRequest",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.import-export.index": [],
    "scm.import-export.documents": [],
    "scm.import-export.documents.create": [],
    "scm.import-export.documents.show": [
        {
            "name": "document",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.import-export.declarations": [],
    "scm.import-export.declarations.create": [],
    "scm.import-export.declarations.show": [
        {
            "name": "declaration",
            "required": true,
            "binding": "id"
        }
    ],
    "scm.import-export.documents.store": [],
    "scm.import-export.declarations.store": [],
    "scm.import-export.documents.download": [
        {
            "name": "document",
            "required": true,
            "binding": "id"
        }
    ],
    "sales.dashboard": [],
    "sales.orders.index": [],
    "sales.orders.create": [],
    "sales.orders.edit": [
        {
            "name": "order",
            "required": true
        }
    ],
    "sales.orders.store": [],
    "sales.orders.update": [
        {
            "name": "order",
            "required": true
        }
    ],
    "sales.orders.destroy": [
        {
            "name": "order",
            "required": true
        }
    ],
    "sales.invoices.index": [],
    "sales.invoices.create": [],
    "sales.invoices.edit": [
        {
            "name": "invoice",
            "required": true
        }
    ],
    "sales.invoices.store": [],
    "sales.invoices.update": [
        {
            "name": "invoice",
            "required": true
        }
    ],
    "sales.invoices.destroy": [
        {
            "name": "invoice",
            "required": true
        }
    ],
    "sales.quotes.index": [],
    "sales.quotes.create": [],
    "sales.quotes.edit": [
        {
            "name": "quote",
            "required": true
        }
    ],
    "sales.quotes.store": [],
    "sales.quotes.update": [
        {
            "name": "quote",
            "required": true
        }
    ],
    "sales.quotes.destroy": [
        {
            "name": "quote",
            "required": true
        }
    ],
    "helpdesk.dashboard": [],
    "helpdesk.tickets.index": [],
    "helpdesk.tickets.create": [],
    "helpdesk.tickets.edit": [
        {
            "name": "ticket",
            "required": true,
            "binding": "id"
        }
    ],
    "helpdesk.tickets.show": [
        {
            "name": "ticket",
            "required": true,
            "binding": "id"
        }
    ],
    "helpdesk.tickets.store": [],
    "helpdesk.tickets.update": [
        {
            "name": "ticket",
            "required": true,
            "binding": "id"
        }
    ],
    "helpdesk.tickets.destroy": [
        {
            "name": "ticket",
            "required": true,
            "binding": "id"
        }
    ],
    "helpdesk.knowledge.index": [],
    "helpdesk.knowledge.create": [],
    "helpdesk.knowledge.edit": [
        {
            "name": "article",
            "required": true
        }
    ],
    "helpdesk.knowledge.show": [
        {
            "name": "article",
            "required": true
        }
    ],
    "helpdesk.knowledge.store": [],
    "helpdesk.knowledge.update": [
        {
            "name": "article",
            "required": true
        }
    ],
    "helpdesk.knowledge.destroy": [
        {
            "name": "article",
            "required": true
        }
    ],
    "assets.dashboard": [],
    "assets.items.index": [],
    "assets.items.create": [],
    "assets.items.edit": [
        {
            "name": "asset",
            "required": true,
            "binding": "id"
        }
    ],
    "assets.items.store": [],
    "assets.items.update": [
        {
            "name": "asset",
            "required": true,
            "binding": "id"
        }
    ],
    "assets.items.destroy": [
        {
            "name": "asset",
            "required": true,
            "binding": "id"
        }
    ],
    "assets.maintenance.index": [],
    "assets.maintenance.create": [],
    "assets.maintenance.edit": [
        {
            "name": "maintenance",
            "required": true
        }
    ],
    "assets.maintenance.store": [],
    "assets.maintenance.update": [
        {
            "name": "maintenance",
            "required": true
        }
    ],
    "assets.maintenance.destroy": [
        {
            "name": "maintenance",
            "required": true
        }
    ],
    "compliance.dashboard": [],
    "compliance.dashboard.index": [],
    "compliance.metrics": [],
    "compliance.export-report": [],
    "compliance.policies.index": [],
    "compliance.policies.create": [],
    "compliance.policies.show": [
        {
            "name": "policy",
            "required": true,
            "binding": "id"
        }
    ],
    "compliance.policies.edit": [
        {
            "name": "policy",
            "required": true,
            "binding": "id"
        }
    ],
    "compliance.policies.store": [],
    "compliance.policies.update": [
        {
            "name": "policy",
            "required": true,
            "binding": "id"
        }
    ],
    "compliance.policies.destroy": [
        {
            "name": "policy",
            "required": true,
            "binding": "id"
        }
    ],
    "compliance.policies.approve": [
        {
            "name": "policy",
            "required": true,
            "binding": "id"
        }
    ],
    "compliance.policies.publish": [
        {
            "name": "policy",
            "required": true,
            "binding": "id"
        }
    ],
    "compliance.policies.archive": [
        {
            "name": "policy",
            "required": true,
            "binding": "id"
        }
    ],
    "compliance.policies.acknowledge": [
        {
            "name": "policy",
            "required": true,
            "binding": "id"
        }
    ],
    "compliance.regulatory.index": [],
    "compliance.regulatory.create": [],
    "compliance.regulatory.show": [
        {
            "name": "requirement",
            "required": true,
            "binding": "id"
        }
    ],
    "compliance.regulatory.edit": [
        {
            "name": "requirement",
            "required": true,
            "binding": "id"
        }
    ],
    "compliance.regulatory.store": [],
    "compliance.regulatory.update": [
        {
            "name": "requirement",
            "required": true,
            "binding": "id"
        }
    ],
    "compliance.regulatory.destroy": [
        {
            "name": "requirement",
            "required": true,
            "binding": "id"
        }
    ],
    "compliance.risks.index": [],
    "compliance.risks.create": [],
    "compliance.risks.show": [
        {
            "name": "risk",
            "required": true
        }
    ],
    "compliance.risks.edit": [
        {
            "name": "risk",
            "required": true
        }
    ],
    "compliance.risks.store": [],
    "compliance.risks.update": [
        {
            "name": "risk",
            "required": true
        }
    ],
    "compliance.risks.destroy": [
        {
            "name": "risk",
            "required": true
        }
    ],
    "compliance.audits.index": [],
    "compliance.audits.create": [],
    "compliance.audits.show": [
        {
            "name": "audit",
            "required": true,
            "binding": "id"
        }
    ],
    "compliance.audits.edit": [
        {
            "name": "audit",
            "required": true,
            "binding": "id"
        }
    ],
    "compliance.audits.store": [],
    "compliance.audits.update": [
        {
            "name": "audit",
            "required": true,
            "binding": "id"
        }
    ],
    "compliance.audits.destroy": [
        {
            "name": "audit",
            "required": true,
            "binding": "id"
        }
    ],
    "compliance.findings.index": [],
    "compliance.findings.create": [],
    "compliance.findings.show": [
        {
            "name": "finding",
            "required": true
        }
    ],
    "compliance.findings.edit": [
        {
            "name": "finding",
            "required": true
        }
    ],
    "compliance.findings.store": [],
    "compliance.findings.update": [
        {
            "name": "finding",
            "required": true,
            "binding": "id"
        }
    ],
    "compliance.findings.destroy": [
        {
            "name": "finding",
            "required": true,
            "binding": "id"
        }
    ],
    "compliance.training.index": [],
    "compliance.training.create": [],
    "compliance.training.show": [
        {
            "name": "training",
            "required": true
        }
    ],
    "compliance.training.edit": [
        {
            "name": "training",
            "required": true
        }
    ],
    "compliance.training.store": [],
    "compliance.training.update": [
        {
            "name": "training",
            "required": true
        }
    ],
    "compliance.training.destroy": [
        {
            "name": "training",
            "required": true
        }
    ],
    "compliance.documents.index": [],
    "compliance.documents.create": [],
    "compliance.documents.show": [
        {
            "name": "document",
            "required": true,
            "binding": "id"
        }
    ],
    "compliance.documents.edit": [
        {
            "name": "document",
            "required": true,
            "binding": "id"
        }
    ],
    "compliance.documents.store": [],
    "compliance.documents.update": [
        {
            "name": "document",
            "required": true,
            "binding": "id"
        }
    ],
    "compliance.documents.destroy": [
        {
            "name": "document",
            "required": true,
            "binding": "id"
        }
    ],
    "quality.dashboard": [],
    "quality.inspections.index": [],
    "quality.inspections.create": [],
    "quality.inspections.edit": [
        {
            "name": "inspection",
            "required": true,
            "binding": "id"
        }
    ],
    "quality.inspections.store": [],
    "quality.inspections.update": [
        {
            "name": "inspection",
            "required": true,
            "binding": "id"
        }
    ],
    "quality.inspections.destroy": [
        {
            "name": "inspection",
            "required": true,
            "binding": "id"
        }
    ],
    "quality.ncr.index": [],
    "quality.ncr.create": [],
    "quality.ncr.edit": [
        {
            "name": "ncr",
            "required": true,
            "binding": "id"
        }
    ],
    "quality.ncr.store": [],
    "quality.ncr.update": [
        {
            "name": "ncr",
            "required": true,
            "binding": "id"
        }
    ],
    "quality.ncr.destroy": [
        {
            "name": "ncr",
            "required": true,
            "binding": "id"
        }
    ],
    "analytics.reports.index": [],
    "analytics.reports.create": [],
    "analytics.reports.edit": [
        {
            "name": "report",
            "required": true,
            "binding": "id"
        }
    ],
    "analytics.reports.show": [
        {
            "name": "report",
            "required": true,
            "binding": "id"
        }
    ],
    "analytics.reports.store": [],
    "analytics.reports.update": [
        {
            "name": "report",
            "required": true,
            "binding": "id"
        }
    ],
    "analytics.reports.destroy": [
        {
            "name": "report",
            "required": true,
            "binding": "id"
        }
    ],
    "analytics.dashboards.index": [],
    "analytics.dashboards.create": [],
    "analytics.dashboards.edit": [
        {
            "name": "dashboard",
            "required": true
        }
    ],
    "analytics.dashboards.show": [
        {
            "name": "dashboard",
            "required": true
        }
    ],
    "analytics.dashboards.store": [],
    "analytics.dashboards.update": [
        {
            "name": "dashboard",
            "required": true
        }
    ],
    "analytics.dashboards.destroy": [
        {
            "name": "dashboard",
            "required": true
        }
    ],
    "analytics.kpi.index": [],
    "analytics.kpi.create": [],
    "analytics.kpi.edit": [
        {
            "name": "kpi",
            "required": true
        }
    ],
    "analytics.kpi.store": [],
    "analytics.kpi.update": [
        {
            "name": "kpi",
            "required": true
        }
    ],
    "analytics.kpi.destroy": [
        {
            "name": "kpi",
            "required": true
        }
    ],
    "admin.settings.crm": [],
    "admin.settings.crm.update": [],
    "admin.settings.finance": [],
    "admin.settings.finance.update": [],
    "admin.settings.pos": [],
    "admin.settings.pos.update": [],
    "admin.settings.inventory": [],
    "admin.settings.inventory.update": [],
    "admin.settings.learning": [],
    "admin.settings.learning.update": [],
    "admin.settings.supply-chain": [],
    "admin.settings.supply-chain.update": [],
    "admin.settings.sales": [],
    "admin.settings.sales.update": [],
    "admin.settings.helpdesk": [],
    "admin.settings.helpdesk.update": [],
    "admin.settings.assets": [],
    "admin.settings.assets.update": [],
    "admin.settings.compliance": [],
    "admin.settings.compliance.update": [],
    "admin.settings.quality": [],
    "admin.settings.quality.update": [],
    "admin.settings.analytics": [],
    "admin.settings.analytics.update": [],
    "procurement.dashboard": [],
    "procurement.purchase-orders.index": [],
    "procurement.purchase-orders.create": [],
    "procurement.purchase-orders.show": [
        {
            "name": "purchaseOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "procurement.purchase-orders.edit": [
        {
            "name": "purchaseOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "procurement.purchase-orders.store": [],
    "procurement.purchase-orders.update": [
        {
            "name": "purchaseOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "procurement.purchase-orders.destroy": [
        {
            "name": "purchaseOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "procurement.purchase-orders.approve": [
        {
            "name": "purchaseOrder",
            "required": true,
            "binding": "id"
        }
    ],
    "procurement.vendors.index": [],
    "procurement.vendors.create": [],
    "procurement.vendors.show": [
        {
            "name": "vendor",
            "required": true,
            "binding": "id"
        }
    ],
    "procurement.vendors.edit": [
        {
            "name": "vendor",
            "required": true,
            "binding": "id"
        }
    ],
    "procurement.vendors.store": [],
    "procurement.vendors.update": [
        {
            "name": "vendor",
            "required": true,
            "binding": "id"
        }
    ],
    "procurement.vendors.delete": [
        {
            "name": "vendor",
            "required": true,
            "binding": "id"
        }
    ],
    "procurement.rfq.index": [],
    "procurement.rfq.create": [],
    "procurement.rfq.show": [
        {
            "name": "rfq",
            "required": true,
            "binding": "id"
        }
    ],
    "procurement.rfq.edit": [
        {
            "name": "rfq",
            "required": true,
            "binding": "id"
        }
    ],
    "procurement.rfq.store": [],
    "procurement.rfq.update": [
        {
            "name": "rfq",
            "required": true,
            "binding": "id"
        }
    ],
    "procurement.rfq.delete": [
        {
            "name": "rfq",
            "required": true,
            "binding": "id"
        }
    ],
    "compliance.documents.download": [
        {
            "name": "document",
            "required": true,
            "binding": "id"
        }
    ],
    "compliance.audits.findings.store": [
        {
            "name": "audit",
            "required": true,
            "binding": "id"
        }
    ],
    "compliance.requirements.index": [],
    "compliance.requirements.create": [],
    "compliance.requirements.show": [
        {
            "name": "requirement",
            "required": true
        }
    ],
    "compliance.requirements.edit": [
        {
            "name": "requirement",
            "required": true
        }
    ],
    "compliance.requirements.store": [],
    "compliance.requirements.update": [
        {
            "name": "requirement",
            "required": true
        }
    ],
    "compliance.requirements.destroy": [
        {
            "name": "requirement",
            "required": true
        }
    ],
    "quality.inspections.show": [
        {
            "name": "inspection",
            "required": true,
            "binding": "id"
        }
    ],
    "quality.ncrs.index": [],
    "quality.ncrs.create": [],
    "quality.ncrs.show": [
        {
            "name": "ncr",
            "required": true,
            "binding": "id"
        }
    ],
    "quality.ncrs.edit": [
        {
            "name": "ncr",
            "required": true,
            "binding": "id"
        }
    ],
    "quality.ncrs.store": [],
    "quality.ncrs.update": [
        {
            "name": "ncr",
            "required": true,
            "binding": "id"
        }
    ],
    "quality.ncrs.destroy": [
        {
            "name": "ncr",
            "required": true,
            "binding": "id"
        }
    ],
    "quality.calibrations.index": [],
    "quality.calibrations.create": [],
    "quality.calibrations.show": [
        {
            "name": "calibration",
            "required": true,
            "binding": "id"
        }
    ],
    "quality.calibrations.edit": [
        {
            "name": "calibration",
            "required": true,
            "binding": "id"
        }
    ],
    "quality.calibrations.store": [],
    "quality.calibrations.update": [
        {
            "name": "calibration",
            "required": true,
            "binding": "id"
        }
    ],
    "quality.calibrations.destroy": [
        {
            "name": "calibration",
            "required": true,
            "binding": "id"
        }
    ],
    "analytics.reports.schedule.form": [
        {
            "name": "report",
            "required": true
        }
    ],
    "analytics.reports.export": [
        {
            "name": "report",
            "required": true,
            "binding": "id"
        }
    ],
    "analytics.reports.schedule": [
        {
            "name": "report",
            "required": true,
            "binding": "id"
        }
    ],
    "analytics.kpi.show": [
        {
            "name": "kpi",
            "required": true
        }
    ],
    "analytics.kpi.log-value": [
        {
            "name": "kpi",
            "required": true
        }
    ],
    "project-management.dashboard": [],
    "project-management.tasks.global": [],
    "project-management.milestones.global": [],
    "project-management.issues.global": [],
    "project-management.resources.global": [],
    "project-management.projects.index": [],
    "project-management.projects.create": [],
    "project-management.projects.edit": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.projects.show": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.projects.store": [],
    "project-management.projects.update": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.projects.destroy": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.milestones.index": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.milestones.create": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.milestones.edit": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "milestone",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.milestones.store": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.milestones.update": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "milestone",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.milestones.destroy": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "milestone",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.tasks.index": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.tasks.create": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.tasks.edit": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.tasks.show": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.tasks.store": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.tasks.update": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.tasks.destroy": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.tasks.assign": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.issues.index": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.issues.create": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.issues.edit": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "issue",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.issues.show": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "issue",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.issues.store": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.issues.update": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "issue",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.issues.destroy": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "issue",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.resources.index": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.resources.store": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.resources.update": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "resource",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.resources.destroy": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "resource",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.time-tracking.index": [],
    "project-management.time-tracking.create": [],
    "project-management.time-tracking.edit": [
        {
            "name": "timeEntry",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.time-tracking.show": [
        {
            "name": "timeEntry",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.time-tracking.reports": [],
    "project-management.time-tracking.store": [],
    "project-management.time-tracking.update": [
        {
            "name": "timeEntry",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.time-tracking.destroy": [
        {
            "name": "timeEntry",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.time-tracking.approve": [
        {
            "name": "timeEntry",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.time-tracking.unapprove": [
        {
            "name": "timeEntry",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.time-tracking.bulk-approve": [],
    "project-management.project-budgets.index": [],
    "project-management.project-budgets.create": [],
    "project-management.project-budgets.edit": [
        {
            "name": "projectBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.project-budgets.show": [
        {
            "name": "projectBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.project-budgets.expenses": [
        {
            "name": "projectBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.project-budgets.reports": [],
    "project-management.project-budgets.store": [],
    "project-management.project-budgets.update": [
        {
            "name": "projectBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.project-budgets.destroy": [
        {
            "name": "projectBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.project-budgets.add-expense": [
        {
            "name": "projectBudget",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.project-budgets.approve-expense": [
        {
            "name": "expense",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.gantt.index": [],
    "project-management.gantt.timeline": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.gantt.critical-path": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.gantt.update-task-dates": [
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.gantt.update-milestone-dates": [
        {
            "name": "milestone",
            "required": true,
            "binding": "id"
        }
    ],
    "project-management.gantt.create-dependency": [],
    "project-management.gantt.delete-dependency": [],
    "project-management.projects.analytics": [],
    "project-management.projects.timeline": [],
    "project-management.projects.matrix": [],
    "project-management.projects.preferences": [],
    "project-management.projects.bulk-update": [],
    "project-management.projects.save-preferences": [],
    "project-management.projects.export": [],
    "hr.dashboard": [],
    "hr.performance.index": [],
    "hr.performance.create": [],
    "hr.performance.store": [],
    "hr.performance.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.performance.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.performance.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.performance.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.performance.templates.index": [],
    "hr.performance.templates.create": [],
    "hr.performance.templates.store": [],
    "hr.performance.templates.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.performance.templates.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.performance.templates.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.performance.templates.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.training.index": [],
    "hr.training.create": [],
    "hr.training.store": [],
    "hr.training.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.training.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.training.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.training.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.training.categories.index": [],
    "hr.training.categories.store": [],
    "hr.training.categories.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.training.categories.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.training.materials.index": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.training.materials.store": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.training.materials.update": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "materialId",
            "required": true
        }
    ],
    "hr.training.materials.destroy": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "materialId",
            "required": true
        }
    ],
    "hr.training.enrollments.index": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.training.enrollments.store": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.training.enrollments.update": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "enrollmentId",
            "required": true
        }
    ],
    "hr.training.enrollments.destroy": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "enrollmentId",
            "required": true
        }
    ],
    "hr.recruitment.index": [],
    "hr.recruitment.store": [],
    "hr.recruitment.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.recruitment.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.recruitment.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.recruitment.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.recruitment.update.ajax": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.recruitment.store.ajax": [],
    "hr.recruitment.data.index": [],
    "hr.recruitment.data.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.recruitment.data.applications": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.recruitment.publish": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.recruitment.unpublish": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.recruitment.close": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.recruitment.statistics": [],
    "hr.recruitment.report": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.recruitment.applications.export": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.recruitment.applications.index": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.recruitment.applications.create": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.recruitment.applications.store": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.recruitment.applications.show": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "applicationId",
            "required": true
        }
    ],
    "hr.recruitment.applications.update": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "applicationId",
            "required": true
        }
    ],
    "hr.recruitment.applications.destroy": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "applicationId",
            "required": true
        }
    ],
    "hr.recruitment.applications.bulk-update": [],
    "hr.recruitment.interviews.index": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "applicationId",
            "required": true
        }
    ],
    "hr.recruitment.interviews.store": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "applicationId",
            "required": true
        }
    ],
    "hr.recruitment.interviews.update": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "applicationId",
            "required": true
        },
        {
            "name": "interviewId",
            "required": true
        }
    ],
    "hr.recruitment.interviews.destroy": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "applicationId",
            "required": true
        },
        {
            "name": "interviewId",
            "required": true
        }
    ],
    "hr.onboarding.index": [],
    "hr.onboarding.create": [],
    "hr.onboarding.store": [],
    "hr.onboarding.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.onboarding.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.onboarding.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.onboarding.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.offboarding.index": [],
    "hr.offboarding.create": [],
    "hr.offboarding.store": [],
    "hr.offboarding.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.offboarding.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.offboarding.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.checklists.index": [],
    "hr.checklists.store": [],
    "hr.checklists.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.checklists.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.skills.index": [],
    "hr.skills.store": [],
    "hr.skills.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.skills.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.competencies.index": [],
    "hr.competencies.store": [],
    "hr.competencies.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.competencies.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.employee.skills.index": [
        {
            "name": "employeeId",
            "required": true
        }
    ],
    "hr.employee.skills.store": [
        {
            "name": "employeeId",
            "required": true
        }
    ],
    "hr.employee.skills.update": [
        {
            "name": "employeeId",
            "required": true
        },
        {
            "name": "skillId",
            "required": true
        }
    ],
    "hr.employee.skills.destroy": [
        {
            "name": "employeeId",
            "required": true
        },
        {
            "name": "skillId",
            "required": true
        }
    ],
    "hr.timeoff.index": [],
    "hr.hr.timeoff.dashboard": [],
    "hr.hr.timeoff.holidays": [],
    "hr.hr.timeoff.leave-requests": [],
    "hr.timeoff.calendar": [],
    "hr.hr.timeoff.balances": [],
    "hr.timeoff.reports": [],
    "hr.timeoff.employee-requests": [],
    "hr.timeoff-legacy.index": [],
    "hr.timeoff-legacy.calendar": [],
    "hr.timeoff-legacy.approvals": [],
    "hr.timeoff-legacy.approve": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.timeoff-legacy.reject": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.timeoff-legacy.reports": [],
    "hr.timeoff-legacy.settings": [],
    "hr.timeoff-legacy.settings.update": [],
    "hr.benefits.index": [],
    "hr.benefits.create": [],
    "hr.benefits.store": [],
    "hr.benefits.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.benefits.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.benefits.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.benefits.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.employee.benefits.index": [
        {
            "name": "employeeId",
            "required": true
        }
    ],
    "hr.employee.benefits.assign": [
        {
            "name": "employeeId",
            "required": true
        }
    ],
    "hr.employee.benefits.update": [
        {
            "name": "employeeId",
            "required": true
        },
        {
            "name": "benefitId",
            "required": true
        }
    ],
    "hr.employee.benefits.remove": [
        {
            "name": "employeeId",
            "required": true
        },
        {
            "name": "benefitId",
            "required": true
        }
    ],
    "hr.timeoff.approvals": [],
    "hr.timeoff.approve": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.timeoff.reject": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.timeoff.settings": [],
    "hr.timeoff.settings.update": [],
    "hr.safety.index": [],
    "hr.safety.incidents.index": [],
    "hr.safety.incidents.create": [],
    "hr.safety.incidents.store": [],
    "hr.safety.incidents.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.safety.incidents.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.safety.inspections.index": [],
    "hr.safety.inspections.create": [],
    "hr.safety.inspections.store": [],
    "hr.safety.inspections.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.safety.inspections.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.safety.training.index": [],
    "hr.safety.training.create": [],
    "hr.safety.training.store": [],
    "hr.safety.training.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.safety.training.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.analytics.index": [],
    "hr.analytics.attendance": [],
    "hr.analytics.performance": [],
    "hr.analytics.recruitment": [],
    "hr.analytics.turnover": [],
    "hr.analytics.training": [],
    "hr.analytics.reports": [],
    "hr.analytics.reports.generate": [],
    "hr.documents.index": [],
    "hr.documents.create": [],
    "hr.documents.store": [],
    "hr.documents.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.documents.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.documents.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.documents.categories.index": [],
    "hr.documents.categories.store": [],
    "hr.documents.categories.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.documents.categories.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.employee.documents.index": [
        {
            "name": "employeeId",
            "required": true
        }
    ],
    "hr.employee.documents.store": [
        {
            "name": "employeeId",
            "required": true
        }
    ],
    "hr.employee.documents.show": [
        {
            "name": "employeeId",
            "required": true
        },
        {
            "name": "documentId",
            "required": true
        }
    ],
    "hr.employee.documents.destroy": [
        {
            "name": "employeeId",
            "required": true
        },
        {
            "name": "documentId",
            "required": true
        }
    ],
    "hr.selfservice.index": [],
    "hr.selfservice.profile": [],
    "hr.selfservice.profile.update": [],
    "hr.selfservice.documents": [],
    "hr.selfservice.benefits": [],
    "hr.selfservice.timeoff": [],
    "hr.selfservice.timeoff.request": [],
    "hr.selfservice.trainings": [],
    "hr.selfservice.payslips": [],
    "hr.selfservice.performance": [],
    "hr.payroll.index": [],
    "hr.payroll.create": [],
    "hr.payroll.store": [],
    "hr.payroll.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.payroll.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.payroll.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.payroll.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.payroll.process": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.payroll.bulk.generate": [],
    "hr.payroll.bulk.process": [],
    "hr.payroll.payslip.generate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.payroll.payslips.bulk.generate": [],
    "hr.payroll.payslip.download": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.payroll.payslip.email": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.payroll.reports": [],
    "hr.payroll.reports.monthly": [],
    "hr.payroll.reports.tax": [],
    "hr.payroll.reports.bank": [],
    "hr.payroll.reports.statutory": [],
    "hr.employees.index": [],
    "hr.employees.paginate": [],
    "hr.employees.stats": [],
    "hr.employees.store": [],
    "hr.employees.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.employees.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.employees.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.employees.restore": [
        {
            "name": "id",
            "required": true
        }
    ],
    "hr.managers.list": [],
    "dms.index": [],
    "dms.documents": [],
    "dms.documents.show": [
        {
            "name": "document",
            "required": true
        }
    ],
    "dms.documents.download": [
        {
            "name": "document",
            "required": true
        }
    ],
    "dms.shared": [],
    "dms.analytics": [],
    "dms.documents.create": [],
    "dms.documents.store": [],
    "dms.documents.update": [
        {
            "name": "document",
            "required": true
        }
    ],
    "dms.documents.share": [
        {
            "name": "document",
            "required": true
        }
    ],
    "dms.documents.destroy": [
        {
            "name": "document",
            "required": true
        }
    ],
    "dms.categories": [],
    "dms.categories.store": [],
    "dms.categories.update": [
        {
            "name": "category",
            "required": true
        }
    ],
    "dms.categories.destroy": [
        {
            "name": "category",
            "required": true
        }
    ],
    "dms.folders": [],
    "dms.folders.store": [],
    "dms.folders.update": [
        {
            "name": "folder",
            "required": true
        }
    ],
    "dms.folders.destroy": [
        {
            "name": "folder",
            "required": true
        }
    ],
    "dms.access-control": [],
    "dms.access-control.update": []
}
}
export {};
